export const DESCRIPTIONS: Record<string, string> = {
  predkosc: "Droga przez czas w ruchu jednostajnym; każdą wielkość policzysz wstecz.",
  "droga-jednostajnie-przyspieszona":
    "Droga z prędkością początkową i stałym przyspieszeniem; czas liczę równaniem kwadratowym.",
  sila: "Druga zasada dynamiki: siła to masa razy przyspieszenie.",
  "energia-kinetyczna": "Połowa masy razy prędkość do kwadratu; prędkość też wstecz.",
  "energia-potencjalna": "Masa razy g razy wysokość (g = 10).",
  gestosc: "Gęstość to masa przez objętość.",
  cisnienie: "Siła nacisku przez powierzchnię.",
  praca: "Praca stałej siły na drodze.",
  pitagoras:
    "W trójkącie prostokątnym kwadrat przeciwprostokątnej to suma kwadratów przyprostokątnych.",
  "pole-trojkata": "Połowa iloczynu podstawy i opuszczonej na nią wysokości.",
  "pole-prostokata": "Iloczyn długości boków.",
  "pole-kola": "Pi razy kwadrat promienia. Promień policzysz też wstecz.",
  "obwod-kola": "Dwa pi er — długość okręgu o danym promieniu.",
  "rownanie-kwadratowe":
    "Delta decyduje o liczbie pierwiastków; wzór działa też dla delty ujemnej i przypadku liniowego.",
  "funkcja-liniowa": "Miejsce zerowe prostej y = ax + b, z wykryciem tożsamości i sprzeczności.",
  procent: "Klasyczne: p procent z liczby x.",
  "ciag-arytmetyczny": "n-ty wyraz i odwrotnie: różnica, pierwszy wyraz albo numer wyrazu.",
  "ciag-geometryczny":
    "n-ty wyraz i pierwszy wyraz; iloraz i numer wymagają pierwiastków i logarytmów.",
  "objetosc-prostopadloscianu": "Iloczyn trzech krawędzi; każdą policzysz wstecz.",
  "objetosc-kuli": "Cztery trzecie pi er do trzeciej; promień też wstecz.",
  "pole-kuli": "Cztery pi er kwadrat — powierzchnia sfery.",
  potega: "Potęgowanie o wykładniku całkowitym, dokładnie na ułamkach.",
  pierwiastek: "Pierwiastek n-tego stopnia z wyciąganiem czynników przed znak.",
  logarytm: "Logarytm o dowolnej podstawie; całkowite wyniki dokładnie.",
  "wartosc-bezwzgledna": "Odległość liczby od zera na osi.",
  "procent-skladany": "Kapitał po n okresach kapitalizacji.",
  "uklad-rownan": "Układ 2 równań liniowych metodą wyznaczników (Cramer).",
  "nierownosc-kwadratowa": "Zbiór rozwiązań z wyborem znaku: >, ≥, <, ≤ albo ≠.",
  "horner-pierwiastki": "Wymierne pierwiastki wielomianu 3. stopnia do rozkładu na czynniki.",
  "postac-kanoniczna": "Wierzchołek paraboli (p, q) ze współczynników.",
  "prawdo-klasyczne": "Liczba zdarzeń sprzyjających przez wszystkie.",
  permutacje: "Na ile sposobów ustawić n różnych elementów w rządku.",
  kombinacje: "Na ile sposobów wybrać k elementów z n (kolejność bez znaczenia).",
  wariacje: "Na ile sposobów wybrać k elementów z n, gdy kolejność ma znaczenie.",
  tales: "Proporcja odcinków na ramionach kąta przeciętych równoległymi.",
  "postacie-kwadratowej": "Ogólna, kanoniczna i iloczynowa z tych samych współczynników naraz.",
  "rozklad-liczby": "Rozkład liczby naturalnej na czynniki pierwsze.",
  "rozklad-wielomianu": "Rozkład wielomianu 3. stopnia na czynniki liniowe (Horner + deflacja).",
  "katy-okrag": "Kąt środkowy jest dwa razy większy od wpisanego opartego na tym samym łuku.",
  "pole-trapez": "Połowa sumy podstaw razy wysokość.",
  "pole-rombu": "Połowa iloczynu przekątnych.",
  "pole-rownoleglobok": "Podstawa razy wysokość.",
  "luk-okregu": "Część obwodu proporcjonalna do kąta środkowego.",
  "wycinek-kola": "Część pola koła proporcjonalna do kąta środkowego.",
  "odl-punktow": "Długość odcinka ze współrzędnych końców (Pitagoras).",
  "srodek-odcinka": "Średnie arytmetyczne współrzędnych końców.",
  "prosta-2-punkty": "Współczynniki prostej y = ax + b przez dwa punkty; wykrywa pionową.",
  prostopadlosc: "Sprawdza, czy proste są równoległe, prostopadłe, czy żadne z tych.",
  "okrag-rownanie": "Równanie okręgu o środku i promieniu, postać kanoniczna.",
  "odl-punkt-prosta": "Najkrótsza odległość punktu od prostej Ax + By + C = 0.",
  graniastoslup: "Pole podstawy razy wysokość.",
  ostroslup: "Jedna trzecia pola podstawy razy wysokość.",
  walec: "Pi er kwadrat razy wysokość; promień i wysokość też wstecz.",
  stozek: "Jedna trzecia objętości walca o tej samej podstawie.",
  newton: "Rozwinięcie (a + b)ⁿ ze współczynnikami dwumianowymi.",
  silnia: "Iloczyn 1·2·…·n, dokładnie na dużych liczbach.",
  szesciany: "Sześcian sumy i różnicy oraz suma i różnica sześcianów naraz.",
  "granica-qn": "Do czego dąży qⁿ, w tym oscylacja dla q = −1.",
  "pochodna-wielomianu": "Pochodna wielomianu 3. stopnia wyraz po wyrazie.",
  "ekstrema-kwadratowej": "Wierzchołek paraboli z informacją minimum/maksimum.",
  "prawdo-warunkowe": "Prawdopodobieństwo A pod warunkiem B i warianty odwrotne.",
  "prawdo-calkowite": "Wzór na prawdopodobieństwo całkowite dla dwóch hipotez.",
  "rownanie-wykladnicze": "Rozwiązanie aˣ = b przez logarytm.",
  "rownanie-logarytmiczne": "Rozwiązanie log_a(x) = c przez definicję.",
  vieta: "Suma i iloczyn pierwiastków bez ich liczenia.",
  "podwojony-kat": "Sinus i cosinus podwojonego kąta z danego kąta.",
  moc: "Praca przez czas.",
  sprawnosc: "Stosunek energii użytecznej do dostarczonej (ułamek; ×100% to procenty).",
  ped: "Masa razy prędkość.",
  zderzenia: "Prędkość zlepionych ciał po zderzeniu niesprężystym.",
  "ruch-okrag": "Prędkość liniowa z promienia i okresu; okres i promień też wstecz.",
  grawitacja: "Siła przyciągania dwóch mas (wynik przybliżony przez stałą G).",
  kepler: "Stosunek kwadratów okresów do sześcianów promieni orbit.",
  archimedes: "Siła wyporu: gęstość cieczy razy g razy objętość zanurzona (g = 10).",
  hydrostatyczne: "Ciśnienie słupa cieczy na głębokości h.",
  cieplo: "Ciepło pobrane lub oddane przy zmianie temperatury.",
  "cieplo-przemiany": "Ciepło topnienia lub parowania masy.",
  ohm: "Natężenie to napięcie przez opór.",
  opor: "Opór z oporności właściwej, długości i przekroju.",
  "moc-pradu": "Moc jako iloczyn napięcia i natężenia.",
  "energia-pradu": "Praca prądu: moc razy czas.",
  lorentz: "Siła na ładunek w polu magnetycznym (v prostopadłe do B).",
  snell: "Stosunek sinusów kąta padania i załamania.",
  soczewki: "Ogniskowa z odległości przedmiotu i obrazu i odwrotnie.",
  powiekszenie: "Stosunek odległości obrazu do przedmiotu.",
  siatka: "Warunek wzmocnienia na siatce dyfrakcyjnej, w tym rząd całkowity.",
  fale: "Prędkość fali to długość razy częstotliwość.",
  "wahadlo-mat": "Okres wahadła matematycznego; długość tylko przybliżona.",
  "wahadlo-sprezyna": "Okres drgań masy na sprężynie.",
  foto: "Bilans energii fotonu: praca wyjścia plus energia kinetyczna.",
  emc2: "Równoważność masy i energii (wynik przybliżony).",
  rozpad: "Ile jąder zostanie po danym czasie (okres połowicznego zaniku).",
  "rzut-poziomy": "Zasięg i czas lotu przy poziomej prędkości początkowej (dokładnie).",
  "moment-sily": "Siła razy ramię.",
  "energia-obrotowa": "Połowa momentu bezwładności razy omega kwadrat.",
  bernoulli: "Ciśnienie w zwężce z zasady zachowania energii strugi.",
  clapeyron: "Stan gazu doskonałego (wynik przybliżony przez R).",
  "pierwsza-zasada": "Przyrost energii wewnętrznej to praca plus ciepło.",
  izobaryczna: "Praca gazu przy stałym ciśnieniu.",
  carnot: "Maksymalna sprawność silnika między temperaturami.",
  rozszerzalnosc: "Wydłużenie pręta przy ogrzaniu.",
  coulomb: "Siła między ładunkami punktowymi (wynik przybliżony).",
  natezenie: "Natężenie pola ładunku punktowego (wynik przybliżony).",
  potencjal: "Potencjał jako praca na jednostkę ładunku.",
  "kondensator-q": "Pojemność z ładunku i napięcia.",
  "kondensator-e": "Energia zgromadzona w kondensatorze.",
  sem: "Prąd z SEM i oporów, w każdą stronę.",
  strumien: "Indukcja razy powierzchnia (pole prostopadłe).",
  faraday: "Moduł SEM indukcji ze zmiany strumienia w czasie.",
  solenoid: "Indukcja w długiej cewce (wynik przybliżony).",
  "sila-elektrodynamiczna": "Siła na przewodnik z prądem w polu magnetycznym.",
  bohr: "Energia n-tej orbity wodoru w elektronowoltach.",
  debroglie: "Długość fali materii cząstki o danym pędzie (wynik przybliżony).",
  "energia-rel": "Energia całkowita z relatywistyki (wynik przybliżony).",
  "zamiana-miary": "Stopnie na radiany dokładnie przez π i z powrotem.",
  "kat-trojkat": "Trzeci kąt z dwóch pozostałych (suma 180°).",
  "kat-miedzy-prostymi": "Ostry kąt między prostymi ze współczynników kierunkowych.",
  "trojkaty-podobne": "Bok odpowiadający ze skali podobieństwa i odwrotnie.",
  "kat-z-bokow": "Kąt z dwóch boków trójkąta prostokątnego (arcus w stopniach).",
  "suma-katow": "Suma kątów wewnętrznych wielokąta i liczba boków wstecz.",
  "znak-wielomianu": "Przedziały znaku wielomianu 3. stopnia z wyborem operatora.",
};

export function getDescription(id: string): string | undefined {
  return DESCRIPTIONS[id];
}
