import { describe, expect, it } from "vitest";
import { FORMULAS } from "./index";
import { solveFormula } from "../solver/solver";
import { renderLatex } from "../katex";

const CASES: [string, string, Record<string, string>][] = [
  ["matematyka", "pitagoras", { a: "3", b: "4", c: "" }],
  ["matematyka", "pitagoras", { a: "", b: "4", c: "5" }],
  ["matematyka", "pitagoras", { a: "3", b: "", c: "5" }],
  ["matematyka", "pole-trojkata", { P: "", a: "4", h: "5" }],
  ["matematyka", "pole-trojkata", { P: "10", a: "", h: "5" }],
  ["matematyka", "pole-trojkata", { P: "10", a: "4", h: "" }],
  ["matematyka", "pole-prostokata", { P: "", a: "3", b: "4" }],
  ["matematyka", "pole-prostokata", { P: "12", a: "", b: "4" }],
  ["matematyka", "pole-prostokata", { P: "12", a: "3", b: "" }],
  ["matematyka", "pole-kola", { P: "", r: "2" }],
  ["matematyka", "pole-kola", { P: "25π", r: "" }],
  ["matematyka", "pole-kola", { P: "25", r: "" }],
  ["matematyka", "obwod-kola", { Ob: "", r: "1" }],
  ["matematyka", "obwod-kola", { Ob: "10π", r: "" }],
  ["matematyka", "obwod-kola", { Ob: "10", r: "" }],
  ["matematyka", "rownanie-kwadratowe", { a: "1", b: "-5", c: "6" }],
  ["matematyka", "rownanie-kwadratowe", { a: "1", b: "0", c: "1" }],
  ["matematyka", "rownanie-kwadratowe", { a: "1", b: "-2", c: "1" }],
  ["matematyka", "rownanie-kwadratowe", { a: "0", b: "2", c: "-4" }],
  ["matematyka", "funkcja-liniowa", { a: "2", b: "-4" }],
  ["matematyka", "funkcja-liniowa", { a: "0", b: "0" }],
  ["matematyka", "funkcja-liniowa", { a: "0", b: "3" }],
  ["matematyka", "procent", { p: "20", x: "50", w: "" }],
  ["matematyka", "procent", { p: "", x: "50", w: "10" }],
  ["matematyka", "procent", { p: "20", x: "", w: "10" }],
  ["matematyka", "ciag-arytmetyczny", { an: "", a1: "2", n: "4", r: "3" }],
  ["matematyka", "ciag-arytmetyczny", { an: "11", a1: "", n: "4", r: "3" }],
  ["matematyka", "ciag-arytmetyczny", { an: "11", a1: "2", n: "", r: "3" }],
  ["matematyka", "ciag-arytmetyczny", { an: "11", a1: "2", n: "4", r: "" }],
  ["matematyka", "ciag-geometryczny", { an: "", a1: "2", q: "3", n: "4" }],
  ["matematyka", "ciag-geometryczny", { an: "54", a1: "", q: "3", n: "4" }],
  ["matematyka", "objetosc-prostopadloscianu", { V: "", a: "2", b: "3", c: "4" }],
  ["matematyka", "objetosc-prostopadloscianu", { V: "24", a: "", b: "3", c: "4" }],
  ["matematyka", "objetosc-kuli", { V: "", r: "3" }],
  ["matematyka", "objetosc-kuli", { V: "36π", r: "" }],
  ["matematyka", "objetosc-kuli", { V: "100", r: "" }],
  ["matematyka", "pole-kuli", { P: "", r: "2" }],
  ["matematyka", "pole-kuli", { P: "16π", r: "" }],
  ["matematyka", "pole-kuli", { P: "50", r: "" }],
  ["fizyka", "predkosc", { v: "", s: "100", t: "4" }],
  ["fizyka", "predkosc", { v: "25", s: "", t: "4" }],
  ["fizyka", "predkosc", { v: "25", s: "100", t: "" }],
  ["fizyka", "droga-jednostajnie-przyspieszona", { s: "", v0: "2", a: "2", t: "3" }],
  ["fizyka", "droga-jednostajnie-przyspieszona", { s: "15", v0: "", a: "2", t: "3" }],
  ["fizyka", "droga-jednostajnie-przyspieszona", { s: "15", v0: "2", a: "", t: "3" }],
  ["fizyka", "droga-jednostajnie-przyspieszona", { s: "4", v0: "0", a: "2", t: "" }],
  ["fizyka", "sila", { F: "", m: "2", a: "5" }],
  ["fizyka", "sila", { F: "10", m: "", a: "2" }],
  ["fizyka", "sila", { F: "10", m: "2", a: "" }],
  ["fizyka", "energia-kinetyczna", { Ek: "", m: "2", v: "10" }],
  ["fizyka", "energia-kinetyczna", { Ek: "100", m: "", v: "10" }],
  ["fizyka", "energia-kinetyczna", { Ek: "100", m: "2", v: "" }],
  ["fizyka", "energia-potencjalna", { Ep: "", m: "2", h: "5" }],
  ["fizyka", "energia-potencjalna", { Ep: "100", m: "", h: "5" }],
  ["fizyka", "energia-potencjalna", { Ep: "100", m: "2", h: "" }],
  ["fizyka", "gestosc", { ro: "", m: "10", V: "2" }],
  ["fizyka", "gestosc", { ro: "5", m: "", V: "2" }],
  ["fizyka", "gestosc", { ro: "5", m: "10", V: "" }],
  ["fizyka", "cisnienie", { p: "", F: "20", S: "4" }],
  ["fizyka", "cisnienie", { p: "5", F: "", S: "4" }],
  ["fizyka", "cisnienie", { p: "5", F: "20", S: "" }],
  ["fizyka", "praca", { W: "", F: "5", s: "4" }],
  ["fizyka", "praca", { W: "20", F: "", s: "4" }],
  ["fizyka", "praca", { W: "20", F: "5", s: "" }],
  ["matematyka", "potega", { p: "2", n: "10", w: "" }],
  ["matematyka", "pierwiastek", { m: "12", n: "2", w: "" }],
  ["matematyka", "pierwiastek", { m: "", n: "3", w: "2" }],
  ["matematyka", "logarytm", { a: "2", b: "8", c: "" }],
  ["matematyka", "logarytm", { a: "2", b: "", c: "3" }],
  ["matematyka", "wartosc-bezwzgledna", { x: "-5" }],
  ["matematyka", "procent-skladany", { K: "", K0: "1000", p: "5", n: "2" }],
  ["matematyka", "uklad-rownan", { a1: "2", b1: "1", c1: "5", a2: "1", b2: "-1", c2: "1" }],
  ["matematyka", "nierownosc-kwadratowa", { a: "1", b: "-5", c: "6" }],
  ["matematyka", "nierownosc-kwadratowa", { a: "1", b: "0", c: "1" }],
  ["matematyka", "horner-pierwiastki", { a: "1", b: "-6", c: "11", d: "-6" }],
  ["matematyka", "postac-kanoniczna", { a: "1", b: "-4", c: "3" }],
  ["matematyka", "prawdo-klasyczne", { A: "3", O: "6" }],
  ["matematyka", "permutacje", { n: "5" }],
  ["matematyka", "kombinacje", { n: "5", k: "2" }],
  ["matematyka", "wariacje", { n: "5", k: "2" }],
  ["matematyka", "tales", { a: "", b: "4", c: "6", d: "8" }],
  ["matematyka", "postacie-kwadratowej", { a: "1", b: "-4", c: "3" }],
  ["matematyka", "postacie-kwadratowej", { a: "1", b: "0", c: "1" }],
  ["matematyka", "rozklad-liczby", { n: "360" }],
  ["matematyka", "rozklad-liczby", { n: "13" }],
  ["matematyka", "rozklad-wielomianu", { a: "1", b: "-6", c: "11", d: "-6" }],
  ["matematyka", "rozklad-wielomianu", { a: "0", b: "1", c: "-5", d: "6" }],
  ["matematyka", "katy-okrag", { alfa: "", beta: "30" }],
  ["matematyka", "katy-okrag", { alfa: "80", beta: "" }],
  ["matematyka", "pole-trapez", { P: "", a: "3", b: "5", h: "4" }],
  ["matematyka", "pole-rombu", { P: "", e: "6", f: "4" }],
  ["matematyka", "pole-rownoleglobok", { P: "", a: "5", h: "3" }],
  ["matematyka", "luk-okregu", { l: "", r: "2", alfa: "90" }],
  ["matematyka", "luk-okregu", { l: "2π", r: "", alfa: "90" }],
  ["matematyka", "wycinek-kola", { P: "", r: "2", alfa: "90" }],
  ["matematyka", "odl-punktow", { x1: "0", y1: "0", x2: "3", y2: "4" }],
  ["matematyka", "srodek-odcinka", { x1: "0", y1: "0", x2: "4", y2: "6" }],
  ["matematyka", "prosta-2-punkty", { x1: "0", y1: "1", x2: "2", y2: "5" }],
  ["matematyka", "prostopadlosc", { a1: "2", a2: "-1/2" }],
  ["matematyka", "okrag-rownanie", { h: "1", k: "-2", r: "3" }],
  ["matematyka", "odl-punkt-prosta", { A: "3", B: "4", C: "-5", x0: "0", y0: "0" }],
  ["matematyka", "graniastoslup", { V: "", Pp: "6", H: "4" }],
  ["matematyka", "ostroslup", { V: "", Pp: "6", H: "3" }],
  ["matematyka", "walec", { V: "", r: "2", H: "3" }],
  ["matematyka", "stozek", { V: "", r: "3", H: "2" }],
  ["matematyka", "newton", { n: "3" }],
  ["matematyka", "silnia", { n: "5" }],
  ["matematyka", "szesciany", { a: "2", b: "1" }],
  ["matematyka", "granica-qn", { q: "1/2" }],
  ["matematyka", "granica-qn", { q: "2" }],
  ["matematyka", "pochodna-wielomianu", { a: "1", b: "0", c: "-3", d: "2" }],
  ["matematyka", "ekstrema-kwadratowej", { a: "1", b: "-4", c: "3" }],
  ["matematyka", "prawdo-warunkowe", { PAB: "1/6", PB: "", P: "1/3" }],
  ["matematyka", "prawdo-calkowite", { PB1: "1/2", PAB1: "1/4", PB2: "1/2", PAB2: "3/4" }],
  ["matematyka", "rownanie-wykladnicze", { a: "2", b: "8" }],
  ["matematyka", "rownanie-logarytmiczne", { a: "10", c: "2" }],
  ["matematyka", "vieta", { a: "1", b: "-5", c: "6" }],
  ["matematyka", "podwojony-kat", { x: "30" }],
  ["fizyka", "moc", { P: "", W: "100", t: "5" }],
  ["fizyka", "sprawnosc", { eta: "", Wu: "40", Wd: "100" }],
  ["fizyka", "ped", { p: "", m: "2", v: "5" }],
  ["fizyka", "zderzenia", { m1: "2", v1: "3", m2: "2", v2: "1" }],
  ["fizyka", "ruch-okrag", { v: "", r: "1", T: "2" }],
  ["fizyka", "grawitacja", { F: "", m: "1000", M: "1000", r: "10" }],
  ["fizyka", "kepler", { T1: "", r1: "1", T2: "1", r2: "8" }],
  ["fizyka", "archimedes", { Fw: "", ro: "1000", V: "2" }],
  ["fizyka", "hydrostatyczne", { p: "", ro: "1000", h: "10" }],
  ["fizyka", "cieplo", { Q: "", m: "2", c: "420", dT: "10" }],
  ["fizyka", "cieplo-przemiany", { Q: "", m: "2", R: "100" }],
  ["fizyka", "ohm", { I: "", U: "12", R: "4" }],
  ["fizyka", "opor", { R: "", ro: "2", l: "10", S: "5" }],
  ["fizyka", "moc-pradu", { P: "", U: "10", I: "2" }],
  ["fizyka", "energia-pradu", { W: "", P: "60", t: "2" }],
  ["fizyka", "lorentz", { F: "", q: "2", v: "3", B: "4" }],
  ["fizyka", "snell", { n: "", alfa: "30", beta: "20" }],
  ["fizyka", "soczewki", { f: "", x: "20", y: "20" }],
  ["fizyka", "powiekszenie", { x: "10", y: "30" }],
  ["fizyka", "siatka", { d: "", alfa: "30", n: "1", lambda: "0.000001" }],
  ["fizyka", "fale", { v: "", lambda: "2", f: "50" }],
  ["fizyka", "wahadlo-mat", { T: "", l: "1" }],
  ["fizyka", "wahadlo-sprezyna", { T: "", m: "1", k: "10" }],
  ["fizyka", "foto", { Ef: "", W: "2", Ek: "3" }],
  ["fizyka", "emc2", { E: "", m: "2" }],
  ["fizyka", "rozpad", { N: "", N0: "100", t: "1", T: "1" }],
  ["fizyka", "rzut-poziomy", { Z: "", v0: "10", h: "5", t: "1" }],
  ["fizyka", "rzut-poziomy", { Z: "10", v0: "5", h: "5", t: "" }],
  ["fizyka", "moment-sily", { M: "", F: "10", r: "2" }],
  ["fizyka", "energia-obrotowa", { E: "", I: "4", w: "3" }],
  ["fizyka", "bernoulli", { p1: "100000", ro: "1000", h1: "5", v1: "2", h2: "3", v2: "1" }],
  ["fizyka", "clapeyron", { p: "", V: "1", n: "1", T: "300" }],
  ["fizyka", "pierwsza-zasada", { dU: "", W: "100", Q: "50" }],
  ["fizyka", "izobaryczna", { W: "", p: "100000", V1: "1", V2: "3" }],
  ["fizyka", "carnot", { eta: "", T1: "600", T2: "300" }],
  ["fizyka", "rozszerzalnosc", { dl: "", alfa: "0.000012", l: "2", dT: "50" }],
  ["fizyka", "coulomb", { F: "", q: "0.000001", Q: "0.000001", r: "1" }],
  ["fizyka", "natezenie", { E: "", Q: "0.000001", r: "1" }],
  ["fizyka", "potencjal", { V: "", W: "10", q: "2" }],
  ["fizyka", "kondensator-q", { C: "", Q: "10", U: "5" }],
  ["fizyka", "kondensator-e", { E: "", C: "2", U: "3" }],
  ["fizyka", "sem", { I: "", E: "12", R: "4", r: "2" }],
  ["fizyka", "strumien", { Phi: "", B: "2", S: "3" }],
  ["fizyka", "faraday", { E: "", dPhi: "10", dt: "2" }],
  ["fizyka", "solenoid", { B: "", N: "100", I: "2", l: "1" }],
  ["fizyka", "sila-elektrodynamiczna", { F: "", B: "2", I: "3", l: "4" }],
  ["fizyka", "bohr", { n: "2" }],
  ["fizyka", "debroglie", { lambda: "", p: "0.000000000000000000001" }],
  ["fizyka", "energia-rel", { E: "", m: "1", v: "10000000" }],
];

describe("latex validity", () => {
  it("covers every registered formula", () => {
    const covered = new Set(CASES.map(([s, id]) => `${s}/${id}`));
    for (const f of FORMULAS) {
      expect(covered.has(`${f.subject}/${f.id}`)).toBe(true);
    }
  });

  it.each(CASES)("%s/%s renders every step without fallback", (subject, id, raw) => {
    const def = FORMULAS.find((f) => f.subject === subject && f.id === id);
    if (!def) throw new Error(`missing ${subject}/${id}`);
    expect(renderLatex(def.latex)).not.toMatch(/latex-fallback/);
    const r = solveFormula(def, raw, 2);
    if (!r.ok) throw new Error(`${subject}/${id}: ${r.error}`);
    for (const s of r.steps) {
      expect(renderLatex(s.body)).not.toMatch(/latex-fallback/);
    }
  });
});
