import { describe, expect, it } from "vitest";
import { FORMULAS } from "./index";
import { solveFormula } from "../solver/solver";
import { renderLatex } from "../katex";

const CASES: [string, string, Record<string, string>][] = [
  ["matematyka", "pitagoras", { a: "3", b: "4", c: "" }],
  ["matematyka", "pitagoras", { a: "", b: "4", c: "5" }],
  ["matematyka", "pitagoras", { a: "3", b: "", c: "5" }],
  ["matematyka", "pole-trojkata", { P: "", a: "4", h: "5" }],
  ["matematyka", "pole-trojkata", { P: "10", a: "", h: "5" }],
  ["matematyka", "pole-trojkata", { P: "10", a: "4", h: "" }],
  ["matematyka", "pole-prostokata", { P: "", a: "3", b: "4" }],
  ["matematyka", "pole-prostokata", { P: "12", a: "", b: "4" }],
  ["matematyka", "pole-prostokata", { P: "12", a: "3", b: "" }],
  ["matematyka", "pole-kola", { P: "", r: "2" }],
  ["matematyka", "pole-kola", { P: "25π", r: "" }],
  ["matematyka", "pole-kola", { P: "25", r: "" }],
  ["matematyka", "obwod-kola", { Ob: "", r: "1" }],
  ["matematyka", "obwod-kola", { Ob: "10π", r: "" }],
  ["matematyka", "obwod-kola", { Ob: "10", r: "" }],
  ["matematyka", "rownanie-kwadratowe", { a: "1", b: "-5", c: "6" }],
  ["matematyka", "rownanie-kwadratowe", { a: "1", b: "0", c: "1" }],
  ["matematyka", "rownanie-kwadratowe", { a: "1", b: "-2", c: "1" }],
  ["matematyka", "rownanie-kwadratowe", { a: "0", b: "2", c: "-4" }],
  ["matematyka", "funkcja-liniowa", { a: "2", b: "-4" }],
  ["matematyka", "funkcja-liniowa", { a: "0", b: "0" }],
  ["matematyka", "funkcja-liniowa", { a: "0", b: "3" }],
  ["matematyka", "procent", { p: "20", x: "50", w: "" }],
  ["matematyka", "procent", { p: "", x: "50", w: "10" }],
  ["matematyka", "procent", { p: "20", x: "", w: "10" }],
  ["matematyka", "ciag-arytmetyczny", { an: "", a1: "2", n: "4", r: "3" }],
  ["matematyka", "ciag-arytmetyczny", { an: "11", a1: "", n: "4", r: "3" }],
  ["matematyka", "ciag-arytmetyczny", { an: "11", a1: "2", n: "", r: "3" }],
  ["matematyka", "ciag-arytmetyczny", { an: "11", a1: "2", n: "4", r: "" }],
  ["matematyka", "ciag-geometryczny", { an: "", a1: "2", q: "3", n: "4" }],
  ["matematyka", "ciag-geometryczny", { an: "54", a1: "", q: "3", n: "4" }],
  ["matematyka", "ciag-geometryczny", { an: "8", a1: "2", q: "", n: "3" }],
  ["matematyka", "ciag-geometryczny", { an: "8", a1: "2", q: "2", n: "" }],
  ["matematyka", "objetosc-prostopadloscianu", { V: "", a: "2", b: "3", c: "4" }],
  ["matematyka", "objetosc-prostopadloscianu", { V: "24", a: "", b: "3", c: "4" }],
  ["matematyka", "objetosc-kuli", { V: "", r: "3" }],
  ["matematyka", "objetosc-kuli", { V: "36π", r: "" }],
  ["matematyka", "objetosc-kuli", { V: "100", r: "" }],
  ["matematyka", "pole-kuli", { P: "", r: "2" }],
  ["matematyka", "pole-kuli", { P: "16π", r: "" }],
  ["matematyka", "pole-kuli", { P: "50", r: "" }],
  ["fizyka", "predkosc", { v: "", s: "100", t: "4" }],
  ["fizyka", "predkosc", { v: "25", s: "", t: "4" }],
  ["fizyka", "predkosc", { v: "25", s: "100", t: "" }],
  ["fizyka", "droga-jednostajnie-przyspieszona", { s: "", v0: "2", a: "2", t: "3" }],
  ["fizyka", "droga-jednostajnie-przyspieszona", { s: "15", v0: "", a: "2", t: "3" }],
  ["fizyka", "droga-jednostajnie-przyspieszona", { s: "15", v0: "2", a: "", t: "3" }],
  ["fizyka", "droga-jednostajnie-przyspieszona", { s: "4", v0: "0", a: "2", t: "" }],
  ["fizyka", "sila", { F: "", m: "2", a: "5" }],
  ["fizyka", "sila", { F: "10", m: "", a: "2" }],
  ["fizyka", "sila", { F: "10", m: "2", a: "" }],
  ["fizyka", "energia-kinetyczna", { Ek: "", m: "2", v: "10" }],
  ["fizyka", "energia-kinetyczna", { Ek: "100", m: "", v: "10" }],
  ["fizyka", "energia-kinetyczna", { Ek: "100", m: "2", v: "" }],
  ["fizyka", "energia-potencjalna", { Ep: "", m: "2", h: "5" }],
  ["fizyka", "energia-potencjalna", { Ep: "100", m: "", h: "5" }],
  ["fizyka", "energia-potencjalna", { Ep: "100", m: "2", h: "" }],
  ["fizyka", "gestosc", { ro: "", m: "10", V: "2" }],
  ["fizyka", "gestosc", { ro: "5", m: "", V: "2" }],
  ["fizyka", "gestosc", { ro: "5", m: "10", V: "" }],
  ["fizyka", "cisnienie", { p: "", F: "20", S: "4" }],
  ["fizyka", "cisnienie", { p: "5", F: "", S: "4" }],
  ["fizyka", "cisnienie", { p: "5", F: "20", S: "" }],
  ["fizyka", "praca", { W: "", F: "5", s: "4" }],
  ["fizyka", "praca", { W: "20", F: "", s: "4" }],
  ["fizyka", "praca", { W: "20", F: "5", s: "" }],
  ["matematyka", "potega", { p: "2", n: "10", w: "" }],
  ["matematyka", "potega", { p: "", n: "3", w: "8" }],
  ["matematyka", "potega", { p: "2", n: "", w: "8" }],
  ["matematyka", "pierwiastek", { m: "12", n: "2", w: "" }],
  ["matematyka", "pierwiastek", { m: "", n: "3", w: "2" }],
  ["matematyka", "pierwiastek", { m: "8", n: "", w: "2" }],
  ["matematyka", "logarytm", { a: "2", b: "8", c: "" }],
  ["matematyka", "logarytm", { a: "2", b: "", c: "3" }],
  ["matematyka", "logarytm", { a: "", b: "8", c: "3" }],
  ["matematyka", "wartosc-bezwzgledna", { x: "-5", a: "0", w: "" }],
  ["matematyka", "wartosc-bezwzgledna", { x: "", a: "2", w: "3" }],
  ["matematyka", "wartosc-bezwzgledna", { x: "5", a: "", w: "3" }],
  ["matematyka", "procent-skladany", { K: "", K0: "1000", p: "5", n: "2" }],
  ["matematyka", "procent-skladany", { K: "110", K0: "100", p: "10", n: "" }],
  ["matematyka", "uklad-rownan", { a1: "2", b1: "1", c1: "5", a2: "1", b2: "-1", c2: "1" }],
  ["matematyka", "nierownosc-kwadratowa", { a: "1", b: "-5", c: "6" }],
  ["matematyka", "nierownosc-kwadratowa", { a: "1", b: "0", c: "1" }],
  ["matematyka", "horner-pierwiastki", { a: "1", b: "-6", c: "11", d: "-6" }],
  ["matematyka", "horner-pierwiastki", { a: "1", b: "-5", c: "6", d: "0" }],
  ["matematyka", "postac-kanoniczna", { a: "1", b: "-4", c: "3" }],
  ["matematyka", "prawdo-klasyczne", { A: "3", O: "6" }],
  ["matematyka", "permutacje", { n: "5" }],
  ["matematyka", "kombinacje", { n: "5", k: "2" }],
  ["matematyka", "wariacje", { n: "5", k: "2" }],
  ["matematyka", "tales", { a: "", b: "4", c: "6", d: "8" }],
  ["matematyka", "postacie-kwadratowej", { a: "1", b: "-4", c: "3" }],
  ["matematyka", "postacie-kwadratowej", { a: "1", b: "0", c: "1" }],
  ["matematyka", "rozklad-liczby", { n: "360" }],
  ["matematyka", "rozklad-liczby", { n: "13" }],
  [
    "matematyka",
    "rozklad-wielomianu",
    { deg: "3", a6: "0", a5: "0", a4: "0", a3: "1", a2: "-6", a1: "11", a0: "-6" },
  ],
  [
    "matematyka",
    "rozklad-wielomianu",
    { deg: "2", a6: "0", a5: "0", a4: "0", a3: "0", a2: "1", a1: "-5", a0: "6" },
  ],
  ["matematyka", "katy-okrag", { alfa: "", beta: "30" }],
  ["matematyka", "katy-okrag", { alfa: "80", beta: "" }],
  ["matematyka", "pole-trapez", { P: "", a: "3", b: "5", h: "4" }],
  ["matematyka", "pole-rombu", { P: "", e: "6", f: "4" }],
  ["matematyka", "pole-rownoleglobok", { P: "", a: "5", h: "3" }],
  ["matematyka", "luk-okregu", { l: "", r: "2", alfa: "90" }],
  ["matematyka", "luk-okregu", { l: "2π", r: "", alfa: "90" }],
  ["matematyka", "wycinek-kola", { P: "", r: "2", alfa: "90" }],
  ["matematyka", "odl-punktow", { x1: "0", y1: "0", x2: "3", y2: "4" }],
  ["matematyka", "srodek-odcinka", { x1: "0", y1: "0", x2: "4", y2: "6" }],
  ["matematyka", "prosta-2-punkty", { x1: "0", y1: "1", x2: "2", y2: "5" }],
  ["matematyka", "prostopadlosc", { a1: "2", a2: "-1/2" }],
  ["matematyka", "okrag-rownanie", { h: "1", k: "-2", r: "3" }],
  ["matematyka", "odl-punkt-prosta", { A: "3", B: "4", C: "-5", x0: "0", y0: "0" }],
  ["matematyka", "graniastoslup", { V: "", Pp: "6", H: "4" }],
  ["matematyka", "ostroslup", { V: "", Pp: "6", H: "3" }],
  ["matematyka", "walec", { V: "", r: "2", H: "3" }],
  ["matematyka", "stozek", { V: "", r: "3", H: "2" }],
  ["matematyka", "newton", { n: "3" }],
  ["matematyka", "silnia", { n: "5" }],
  ["matematyka", "szesciany", { a: "2", b: "1" }],
  ["matematyka", "granica-qn", { q: "1/2" }],
  ["matematyka", "granica-qn", { q: "2" }],
  ["matematyka", "pochodna-wielomianu", { a: "1", b: "0", c: "-3", d: "2" }],
  ["matematyka", "ekstrema-kwadratowej", { a: "1", b: "-4", c: "3" }],
  ["matematyka", "prawdo-warunkowe", { PAB: "1/6", PB: "", P: "1/3" }],
  ["matematyka", "prawdo-calkowite", { PB1: "1/2", PAB1: "1/4", PB2: "1/2", PAB2: "3/4" }],
  ["matematyka", "rownanie-wykladnicze", { a: "2", b: "8" }],
  ["matematyka", "rownanie-logarytmiczne", { a: "10", c: "2" }],
  ["matematyka", "vieta", { a: "1", b: "-5", c: "6" }],
  ["matematyka", "podwojony-kat", { x: "30" }],
  ["fizyka", "moc", { P: "", W: "100", t: "5" }],
  ["fizyka", "sprawnosc", { eta: "", Wu: "40", Wd: "100" }],
  ["fizyka", "ped", { p: "", m: "2", v: "5" }],
  ["fizyka", "zderzenia", { m1: "2", v1: "3", m2: "2", v2: "1" }],
  ["fizyka", "ruch-okrag", { v: "", r: "1", T: "2" }],
  ["fizyka", "grawitacja", { F: "", m: "1000", M: "1000", r: "10" }],
  ["fizyka", "kepler", { T1: "", r1: "1", T2: "1", r2: "8" }],
  ["fizyka", "archimedes", { Fw: "", ro: "1000", V: "2" }],
  ["fizyka", "hydrostatyczne", { p: "", ro: "1000", h: "10" }],
  ["fizyka", "cieplo", { Q: "", m: "2", c: "420", dT: "10" }],
  ["fizyka", "cieplo-przemiany", { Q: "", m: "2", R: "100" }],
  ["fizyka", "ohm", { I: "", U: "12", R: "4" }],
  ["fizyka", "opor", { R: "", ro: "2", l: "10", S: "5" }],
  ["fizyka", "moc-pradu", { P: "", U: "10", I: "2" }],
  ["fizyka", "energia-pradu", { W: "", P: "60", t: "2" }],
  ["fizyka", "lorentz", { F: "", q: "2", v: "3", B: "4" }],
  ["fizyka", "snell", { n: "", alfa: "30", beta: "20" }],
  ["fizyka", "soczewki", { f: "", x: "20", y: "20" }],
  ["fizyka", "powiekszenie", { x: "10", y: "30" }],
  ["fizyka", "siatka", { d: "", alfa: "30", n: "1", lambda: "0.000001" }],
  ["fizyka", "fale", { v: "", lambda: "2", f: "50" }],
  ["fizyka", "wahadlo-mat", { T: "", l: "1" }],
  ["fizyka", "wahadlo-sprezyna", { T: "", m: "1", k: "10" }],
  ["fizyka", "foto", { Ef: "", W: "2", Ek: "3" }],
  ["fizyka", "emc2", { E: "", m: "2" }],
  ["fizyka", "rozpad", { N: "", N0: "100", t: "1", T: "1" }],
  ["fizyka", "rzut-poziomy", { Z: "", v0: "10", h: "5", t: "1" }],
  ["fizyka", "rzut-poziomy", { Z: "10", v0: "5", h: "5", t: "" }],
  ["fizyka", "moment-sily", { M: "", F: "10", r: "2" }],
  ["fizyka", "energia-obrotowa", { E: "", I: "4", w: "3" }],
  ["fizyka", "bernoulli", { p1: "100000", ro: "1000", h1: "5", v1: "2", h2: "3", v2: "1" }],
  ["fizyka", "clapeyron", { p: "", V: "1", n: "1", T: "300" }],
  ["fizyka", "pierwsza-zasada", { dU: "", W: "100", Q: "50" }],
  ["fizyka", "izobaryczna", { W: "", p: "100000", V1: "1", V2: "3" }],
  ["fizyka", "carnot", { eta: "", T1: "600", T2: "300" }],
  ["fizyka", "rozszerzalnosc", { dl: "", alfa: "0.000012", l: "2", dT: "50" }],
  ["fizyka", "coulomb", { F: "", q: "0.000001", Q: "0.000001", r: "1" }],
  ["fizyka", "natezenie", { E: "", Q: "0.000001", r: "1" }],
  ["fizyka", "potencjal", { V: "", W: "10", q: "2" }],
  ["fizyka", "kondensator-q", { C: "", Q: "10", U: "5" }],
  ["fizyka", "kondensator-e", { E: "", C: "2", U: "3" }],
  ["fizyka", "sem", { I: "", E: "12", R: "4", r: "2" }],
  ["fizyka", "strumien", { Phi: "", B: "2", S: "3" }],
  ["fizyka", "faraday", { E: "", dPhi: "10", dt: "2" }],
  ["fizyka", "solenoid", { B: "", N: "100", I: "2", l: "1" }],
  ["fizyka", "sila-elektrodynamiczna", { F: "", B: "2", I: "3", l: "4" }],
  ["fizyka", "bohr", { n: "2" }],
  ["fizyka", "debroglie", { lambda: "", p: "0.000000000000000000001" }],
  ["fizyka", "energia-rel", { E: "", m: "1", v: "10000000" }],
  ["matematyka", "zamiana-miary", { deg: "180", rad: "" }],
  ["matematyka", "zamiana-miary", { deg: "", rad: "3.141592653589793" }],
  ["matematyka", "kat-trojkat", { alfa: "60", beta: "70", gamma: "" }],
  ["matematyka", "kat-miedzy-prostymi", { a1: "0", a2: "1" }],
  ["matematyka", "kat-miedzy-prostymi", { a1: "1", a2: "-1" }],
  ["matematyka", "kat-miedzy-prostymi", { a1: "2", a2: "2" }],
  ["matematyka", "trojkaty-podobne", { k: "2", x: "3", y: "" }],
  ["matematyka", "trojkaty-podobne", { k: "", x: "3", y: "6" }],
  ["matematyka", "kat-z-bokow", { jak: "sin⁻¹ (x/y)", x: "1", y: "2" }],
  ["matematyka", "kat-z-bokow", { jak: "cos⁻¹ (x/y)", x: "1", y: "2" }],
  ["matematyka", "kat-z-bokow", { jak: "tan⁻¹ (x/y)", x: "1", y: "1" }],
  ["matematyka", "suma-katow", { n: "5", S: "" }],
  ["matematyka", "suma-katow", { n: "", S: "540" }],
  ["matematyka", "nierownosc-kwadratowa", { a: "1", b: "-5", c: "6", op: ">" }],
  ["matematyka", "nierownosc-kwadratowa", { a: "1", b: "-5", c: "6", op: "≥" }],
  ["matematyka", "nierownosc-kwadratowa", { a: "1", b: "-5", c: "6", op: "<" }],
  ["matematyka", "nierownosc-kwadratowa", { a: "1", b: "-5", c: "6", op: "≤" }],
  ["matematyka", "nierownosc-kwadratowa", { a: "1", b: "-5", c: "6", op: "≠" }],
  ["matematyka", "nierownosc-kwadratowa", { a: "1", b: "0", c: "1", op: "≠" }],
  ["matematyka", "znak-wielomianu", { a: "1", b: "-6", c: "11", d: "-6", op: ">" }],
  ["matematyka", "znak-wielomianu", { a: "1", b: "-6", c: "11", d: "-6", op: "≤" }],
  ["chemia", "mol", { n: "", m: "18", M: "18" }],
  ["chemia", "mol", { n: "1", m: "", M: "18" }],
  ["chemia", "mol", { n: "1", m: "18", M: "" }],
  ["chemia", "stezenie-molowe", { C: "", n: "2", V: "1" }],
  ["chemia", "stezenie-molowe", { C: "2", n: "", V: "1" }],
  ["chemia", "stezenie-molowe", { C: "2", n: "2", V: "" }],
  ["chemia", "stezenie-procentowe", { Cp: "", ms: "5", mr: "100" }],
  ["chemia", "stezenie-procentowe", { Cp: "5", ms: "", mr: "100" }],
  ["chemia", "stezenie-procentowe", { Cp: "5", ms: "5", mr: "" }],
  ["chemia", "rozcienczanie", { C1: "1", V1: "0.5", C2: "", V2: "1" }],
  ["chemia", "rozcienczanie", { C1: "", V1: "0.5", C2: "0.5", V2: "1" }],
  ["chemia", "rozcienczanie", { C1: "1", V1: "", C2: "0.5", V2: "1" }],
  ["chemia", "ph", { pH: "", H: "0.001" }],
  ["chemia", "ph", { pH: "3", H: "" }],
  ["chemia", "wydajnosc", { W: "", mp: "8", mt: "10" }],
  ["chemia", "wydajnosc", { W: "80", mp: "", mt: "10" }],
  ["chemia", "wydajnosc", { W: "80", mp: "8", mt: "" }],
  ["chemia", "mieszanie", { C1: "10", m1: "100", C2: "20", m2: "200" }],
  ["chemia", "kc", { a: "1", b: "1", c: "1", d: "1", CA: "1", CB: "1", CC: "1", CD: "1" }],
  ["chemia", "dysocjacja", { alfa: "", cz: "0.1", c0: "1" }],
  ["chemia", "dysocjacja", { alfa: "0.1", cz: "", c0: "1" }],
  ["chemia", "dysocjacja", { alfa: "0.1", cz: "0.1", c0: "" }],
  ["chemia", "iloczyn", { Ks: "", A: "0.00001", B: "0.00001" }],
  ["chemia", "iloczyn", { Ks: "0.0000000001", A: "", B: "0.00001" }],
  ["chemia", "iloczyn", { Ks: "0.0000000001", A: "0.00001", B: "" }],
  ["chemia", "ogniwo", { E: "", Ekat: "0.34", Ean: "-0.76" }],
  ["chemia", "ogniwo", { E: "1.1", Ekat: "", Ean: "-0.76" }],
  ["chemia", "ogniwo", { E: "1.1", Ekat: "0.34", Ean: "" }],
  ["chemia", "elektroliza", { m: "", k: "0.001", I: "2", t: "100" }],
  ["chemia", "elektroliza", { m: "0.2", k: "", I: "2", t: "100" }],
  ["chemia", "elektroliza", { m: "0.2", k: "0.001", I: "", t: "100" }],
  ["chemia", "elektroliza", { m: "0.2", k: "0.001", I: "2", t: "" }],
  ["chemia", "bufor", { pH: "", pKa: "4.76", Cs: "0.1", Ck: "0.1" }],
  ["chemia", "bufor", { pH: "4.76", pKa: "", Cs: "0.1", Ck: "0.1" }],
  ["chemia", "bufor", { pH: "4.76", pKa: "4.76", Cs: "", Ck: "0.1" }],
  ["chemia", "bufor", { pH: "4.76", pKa: "4.76", Cs: "0.1", Ck: "" }],
  ["matematyka", "delta", { a: "1", b: "-5", c: "6" }],
  ["matematyka", "delta", { a: "1", b: "0", c: "1" }],
  ["matematyka", "delta", { a: "1", b: "2", c: "1" }],
  ["matematyka", "kwadratowa-iloczynowa", { a: "1", b: "-5", c: "6" }],
  ["matematyka", "kwadratowa-iloczynowa", { a: "1", b: "0", c: "1" }],
  ["matematyka", "kwadratowa-iloczynowa", { a: "1", b: "2", c: "1" }],
  ["matematyka", "kwadratowa-ogolna", { a: "1", x1: "2", x2: "3" }],
  ["matematyka", "kwadratowa-ogolna", { a: "1", x1: "2", x2: "2" }],
  ["matematyka", "kwadrat-sumy-roznicy", { a: "2", b: "3" }],
  ["matematyka", "roznica-kwadratow", { a: "5", b: "3" }],
  ["matematyka", "wzor-herona", { a: "3", b: "4", c: "5" }],
  ["matematyka", "wzor-herona", { a: "5", b: "5", c: "6" }],
  [
    "matematyka",
    "wyodrebnianie-czynnika",
    { c1: "6", k1: "3", c2: "9", k2: "2", c3: "12", k3: "1" },
  ],
  ["matematyka", "grupowanie", { a: "1", b: "2", c: "2", d: "4" }],
  [
    "matematyka",
    "rozklad-wielomianu",
    { deg: "4", a6: "0", a5: "0", a4: "1", a3: "0", a2: "-5", a1: "0", a0: "4" },
  ],
  [
    "matematyka",
    "dzielenie-wielomianow",
    { degW: "3", w5: "0", w4: "0", w3: "1", w2: "-6", w1: "11", w0: "-6", p1: "1", p0: "-1" },
  ],
  [
    "matematyka",
    "schemat-hornera",
    { deg: "3", a6: "0", a5: "0", a4: "0", a3: "1", a2: "-6", a1: "11", a0: "-6", x0: "1" },
  ],
  ["matematyka", "dodawanie-pisemne", { a: "123", b: "456" }],
  ["matematyka", "odejmowanie-pisemne", { a: "456", b: "123" }],
  ["matematyka", "mnozenie-pisemne", { a: "123", b: "45" }],
  ["matematyka", "dzielenie-pisemne", { a: "1234", b: "12" }],
  ["matematyka", "dzielenie-pisemne", { a: "12.5", b: "2.5" }],
  ["matematyka", "suma-ciagu-arytmetycznego", { Sn: "", a1: "2", an: "20", n: "10" }],
  ["matematyka", "suma-ciagu-arytmetycznego", { Sn: "110", a1: "", an: "20", n: "10" }],
  ["matematyka", "suma-ciagu-arytmetycznego", { Sn: "110", a1: "2", an: "20", n: "" }],
  ["matematyka", "suma-ciagu-geometrycznego", { Sn: "", a1: "2", q: "3", n: "4" }],
  ["matematyka", "suma-ciagu-geometrycznego", { Sn: "80", a1: "", q: "3", n: "4" }],
  ["matematyka", "suma-ciagu-geometrycznego", { Sn: "80", a1: "2", q: "3", n: "" }],
  ["matematyka", "suma-ciagu-geometrycznego", { Sn: "80", a1: "2", q: "", n: "4" }],
  ["matematyka", "szereg-geometryczny", { S: "", a1: "1", q: "0.5" }],
  ["matematyka", "szereg-geometryczny", { S: "2", a1: "", q: "0.5" }],
  ["matematyka", "szereg-geometryczny", { S: "2", a1: "1", q: "" }],
  ["matematyka", "tw-sinusow", { a: "", alfa: "30", R: "5" }],
  ["matematyka", "tw-sinusow", { a: "5", alfa: "", R: "5" }],
  ["matematyka", "tw-sinusow", { a: "5", alfa: "30", R: "" }],
  ["matematyka", "tw-cosinusow", { c: "", a: "3", b: "4", gamma: "90" }],
  ["matematyka", "tw-cosinusow", { c: "5", a: "3", b: "4", gamma: "" }],
  ["matematyka", "tw-cosinusow", { c: "5", a: "", b: "4", gamma: "90" }],
  ["matematyka", "okrag-opisany-wpisany", { a: "3", b: "4", c: "5" }],
  ["matematyka", "schemat-bernoulliego", { n: "5", k: "2", p: "0.5" }],
  ["fizyka", "predkosc-chwilowa", { v: "", v0: "2", a: "3", t: "4" }],
  ["fizyka", "predkosc-chwilowa", { v: "14", v0: "", a: "3", t: "4" }],
  ["fizyka", "predkosc-chwilowa", { v: "14", v0: "2", a: "", t: "4" }],
  ["fizyka", "predkosc-chwilowa", { v: "14", v0: "2", a: "3", t: "" }],
  ["fizyka", "energia-wewnetrzna", { U: "", n: "2", T: "300" }],
  ["fizyka", "energia-wewnetrzna", { U: "7479", n: "", T: "300" }],
  ["fizyka", "energia-wewnetrzna", { U: "7479", n: "2", T: "" }],
  ["fizyka", "oporniki-szeregowo", { Rz: "", R1: "10", R2: "20" }],
  ["fizyka", "oporniki-szeregowo", { Rz: "30", R1: "", R2: "20" }],
  ["fizyka", "oporniki-rownolegle", { Rz: "", R1: "10", R2: "10" }],
  ["fizyka", "oporniki-rownolegle", { Rz: "5", R1: "", R2: "10" }],
  ["fizyka", "doppler", { fp: "", f: "440", vs: "34" }],
  ["fizyka", "doppler", { fp: "484", f: "", vs: "34" }],
  ["fizyka", "doppler", { fp: "484", f: "440", vs: "" }],
  ["fizyka", "kat-graniczny", { alfa: "", n: "1.5" }],
  ["fizyka", "kat-graniczny", { alfa: "42", n: "" }],
  ["matematyka", "statystyka", { xs: "2;4;4;5" }],
  ["matematyka", "romb-bok", { P: "", a: "5", h: "4" }],
  ["matematyka", "romb-bok", { P: "20", a: "", h: "4" }],
  ["matematyka", "suma-katow-tryg", { alfa: "30", beta: "60", fn: "sin", pm: "+" }],
  ["fizyka", "boyle", { p1: "", V1: "2", p2: "4", V2: "1" }],
  ["fizyka", "boyle", { p1: "2", V1: "", p2: "4", V2: "1" }],
  ["fizyka", "gaylussac", { V1: "", T1: "300", V2: "2", T2: "600" }],
  ["fizyka", "gaylussac", { V1: "1", T1: "", V2: "2", T2: "600" }],
  ["fizyka", "charles", { p1: "", T1: "300", p2: "200", T2: "600" }],
  ["fizyka", "charles", { p1: "100", T1: "", p2: "200", T2: "600" }],
  ["geografia", "skala-mapy", { M: "", drzecz: "100000", dmapy: "1" }],
  ["geografia", "skala-mapy", { M: "100000", drzecz: "", dmapy: "1" }],
  ["geografia", "skala-mapy", { M: "100000", drzecz: "100000", dmapy: "" }],
  ["geografia", "gestosc-zaludnienia", { g: "", L: "1000", P: "10" }],
  ["geografia", "gestosc-zaludnienia", { g: "100", L: "", P: "10" }],
  ["geografia", "gestosc-zaludnienia", { g: "100", L: "1000", P: "" }],
  ["geografia", "przyrost-naturalny", { PN: "", U: "120", Z: "100" }],
  ["geografia", "przyrost-naturalny", { PN: "20", U: "", Z: "100" }],
  ["geografia", "przyrost-naturalny", { PN: "20", U: "120", Z: "" }],
  ["geografia", "saldo-migracji", { S: "", I: "50", E: "30" }],
  ["geografia", "saldo-migracji", { S: "20", I: "", E: "30" }],
  ["geografia", "saldo-migracji", { S: "20", I: "50", E: "" }],
  ["geografia", "przyrost-rzeczywisty", { PR: "", PN: "20", S: "5" }],
  ["geografia", "przyrost-rzeczywisty", { PR: "25", PN: "", S: "5" }],
  ["geografia", "przyrost-rzeczywisty", { PR: "25", PN: "20", S: "" }],
  ["geografia", "deniwelacja", { D: "", Hmax: "500", Hmin: "200" }],
  ["geografia", "deniwelacja", { D: "300", Hmax: "", Hmin: "200" }],
  ["geografia", "deniwelacja", { D: "300", Hmax: "500", Hmin: "" }],
  ["geografia", "amplituda-temperatur", { A: "", Tmax: "25", Tmin: "10" }],
  ["geografia", "amplituda-temperatur", { A: "15", Tmax: "", Tmin: "10" }],
  ["geografia", "amplituda-temperatur", { A: "15", Tmax: "25", Tmin: "" }],
  ["geografia", "nachylenie-stoku", { n: "", D: "50", d: "500" }],
  ["geografia", "nachylenie-stoku", { n: "10", D: "", d: "500" }],
  ["geografia", "nachylenie-stoku", { n: "10", D: "50", d: "" }],
  ["geografia", "wskaznik-urbanizacji", { U: "", Lm: "60", L: "100" }],
  ["geografia", "wskaznik-urbanizacji", { U: "60", Lm: "", L: "100" }],
  ["geografia", "wskaznik-urbanizacji", { U: "60", Lm: "60", L: "" }],
  ["geografia", "stopa-bezrobocia", { u: "", B: "5", A: "100" }],
  ["geografia", "stopa-bezrobocia", { u: "5", B: "", A: "100" }],
  ["geografia", "stopa-bezrobocia", { u: "5", B: "5", A: "" }],
  ["geografia", "pkb-per-capita", { PKBpc: "", PKB: "1000", L: "10" }],
  ["geografia", "pkb-per-capita", { PKBpc: "100", PKB: "", L: "10" }],
  ["geografia", "pkb-per-capita", { PKBpc: "100", PKB: "1000", L: "" }],
  ["geografia", "wspolczynnik-feminizacji", { Wf: "", K: "105", M: "100" }],
  ["geografia", "wspolczynnik-feminizacji", { Wf: "105", K: "", M: "100" }],
  ["geografia", "wspolczynnik-feminizacji", { Wf: "105", K: "105", M: "" }],
  ["geografia", "wspolczynnik-przyrostu", { r: "", PN: "20", L: "1000" }],
  ["geografia", "wspolczynnik-przyrostu", { r: "20", PN: "", L: "1000" }],
  ["geografia", "wspolczynnik-przyrostu", { r: "20", PN: "20", L: "" }],
  ["geografia", "czas-sloneczny", { dt: "", dlambda: "15", k: "4" }],
  ["geografia", "czas-sloneczny", { dt: "60", dlambda: "", k: "4" }],
  ["geografia", "czas-sloneczny", { dt: "60", dlambda: "15", k: "" }],
  ["geografia", "bilans-wodny", { B: "", P: "800", E: "500" }],
  ["geografia", "bilans-wodny", { B: "300", P: "", E: "500" }],
  ["geografia", "bilans-wodny", { B: "300", P: "800", E: "" }],
];

describe("latex validity", () => {
  it("covers every registered formula", () => {
    const covered = new Set(CASES.map(([s, id]) => `${s}/${id}`));
    for (const f of FORMULAS) {
      expect(covered.has(`${f.subject}/${f.id}`)).toBe(true);
    }
  });

  it.each(CASES)("%s/%s renders every step without fallback", (subject, id, raw) => {
    const def = FORMULAS.find((f) => f.subject === subject && f.id === id);
    if (!def) throw new Error(`missing ${subject}/${id}`);
    expect(renderLatex(def.latex)).not.toMatch(/latex-fallback/);
    const r = solveFormula(def, raw, 2);
    if (!r.ok) throw new Error(`${subject}/${id}: ${r.error}`);
    for (const s of r.steps) {
      expect(renderLatex(s.body)).not.toMatch(/latex-fallback/);
    }
  });
});
